### ISSUE TITLE
CommonLibSSE Files Not Updated

### ISSUE THREAD

**Issue by Velgus** [SniffleMan/GlowBeGoneSSE#1]
So I'm trying to make a 1.5.53 version for all the people whining on Nexus.

That said, I can't successfully compile it, as there doesn't appear to be RE/TESEffectShader.h (and possibly more files?)

**Comment by SniffleMan** [comment]
You need https://github.com/SniffleMan/CommonLibSSE

**Comment by Velgus** [comment]
Yeah I know, I have it. It's not up to date though, the latest "master" version is missing files for GlowBeGoneSSE.

**Comment by SniffleMan** [comment]
try it now

**Comment by Velgus** [comment]
Just saw the update go up - thanks!

**Comment by stevestock** [comment]
Hey @Velgus 
I wanted to see if you could help me, I have some questions about the USSEP VR Patch... check your reddit PMs or let me know if there’s a better way I can contact you. Thanks!
